//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDAC.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventarios
    {
        public int Idinventario { get; set; }
        public int Utilizado { get; set; }
        public int FK_estado { get; set; }
        public int FK_DetalleCompra { get; set; }
    
        public virtual DetallesCompras DetallesCompras { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
