//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDAC.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int idPago { get; set; }
        public string mes { get; set; }
        public decimal montoBase { get; set; }
        public decimal montoCancelado { get; set; }
        public decimal montoPendiente { get; set; }
        public Nullable<decimal> mora { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int FK_estado { get; set; }
        public int FK_consumidor { get; set; }
    
        public virtual Consumidores Consumidores { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
