//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDAC.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetirosInventario
    {
        public int idRetiro { get; set; }
        public string cantidad { get; set; }
        public string descripcion { get; set; }
        public string motivo { get; set; }
        public string precioUnidad { get; set; }
        public string subtotal { get; set; }
        public string date { get; set; }
    }
}
